### PR TITLE
Mod loading from save refactor

### PR DESCRIPTION
**Pull request by sean-callahan**
* Removed dependency on semver library
* Moved to new version struct types in level.dat structure
    - added version24, version48, and version64 types and marshallers
* Fixed UI to reflect new json schema
    - removed `num_mods`
    - versions are now 3-element arrays instead of objects

### CODE REVIEW

**Comment by knoxfighter** [comment]
Wow, that was fast.
First of all, thank you very much for this rework.

Since i dont know, how to write commands on files (not lines), here is the review for the `factorio_save.go`:

I originally liked the idea to have it in its own package, so the code cade easily be copied to other projects. In the beginning i also thought about, making it its own github-repo. But with the Version struct it is also ok that it is in the default package.

Another thing i dont like, is that you often use variables that only have a single character as their name. I dont like this codestyle, its hard to read others code, when the variables are not descriptive.

Optimization of the readOptimUint32() function, so we get rid of the duplicated code. Somthing like:
```
if optimized {
    var b [4]byte
    _, err := r.Read(b[:1])
    if err != nil {
        return 0, err
    }
    if b[0] != 0xFF {
        return uint32(b[0]), nil
    }
    _, err = r.Read(b[:4])
    if err != nil {
        return 0, err
    }
    return binary.LittleEndian.Uint32(b[:4]), nil
} else {
    var b [4]byte
    _, err := r.Read(b[:])
    if err != nil {
        return 0, fmt.Errorf("failed to read string length: %v", err)
    }
    return uint32(binary.LittleEndian.Uint32(b[:])), nil
}
```


Now to the code:
You want to implement the original (https://forums.factorio.com/viewtopic.php?f=5&t=8568&p=392403&hilit=read+mods+from+save#p356937) idead to be compatible to all version. So you defined most things that are needed for 0.14, 0.15 and 0.16.
If lower versions should supported, also the following fields have to be added:
- AllowedCommands: Spicial behaviour for versions <= 0.13.0.87:
  ```
  self.allowed_commands = ds.read_u8()
    if ds.version <= (0, 13, 0, 87):
        if not self.allowed_commands:
            self.allowed_commands = 2
        else:
            self.allowed_commands = 1
  ```
- num_stats:
  ```
  self.stats = {}
    if ds.version <= (0, 13, 0, 42):
        num_stats = ds.read_u32()
        for i in range(num_stats):
            force_id = ds.read_u8()
            self.stats[force_id] = []
            for j in range(3):
                st = {}
                length = ds.read_u32()
                for k in range(length):
                    k = ds.read_u16()
                    v = ds.read_u32()
                    st[k] = v
                self.stats[force_id].append(st)
  ```

I would also recommend re-adding the compatibility-check. So we can detect all not supported versions, like 0.17 or 0.13 (or whatever you choose to implement to lower the version).

**Further review will come tomorrow or so and in following comments :)**

**Comment by knoxfighter** [comment]
Review for `mods_handler.go`:

I normally try to keep the HandlerFunc as small as possible. Only the message and answer handling should be in there, IMHO. We doesn't have styling conventions here, so its not really relevant, if you change it :)

**Comment by nickcraig** [comment]
Only a complete jackass would single character variables

**Comment by knoxfighter** [comment]
Agin, thanks for the fast changes!

That fles are looking good now. One last thing, i am pretty sure, that with factorio version 0.17, they have changes in the level.dat, so our code will fail to read from those files. And i like to get the knowledge to the user, what did go wrong.

We need only 0.13.0.0 upwards, cause the mod-portal got introduced in version 0.13. Before that, all mods had to be downloaded and installed manually from the page, the modowner had or choose.

`removed num_mods` i dont understand why you wrote that, in you first comment. I cant see anything that even has this name in your changes.

I finally had time to test the functionality and tried out different saves from different game versions. I also decided to write a test for it, to test it automatically. I created a pull request for that files into your pull request branch :)
I found an error, when trying to read a 0.13 save. Seems like its a few bytes off. So it tries to read over 50000 mods.

**Comment by sean-callahan** [comment]
Those tests worked great for debugging! Thanks for setting that up.

Looks like 0.13 didn't like the new way of reading optimized string lengths and mod count. Which would explain the byte offset issues. My most recent commit fixed the 0.13 tests and read the file properly (no more deadlocks!).

Regarding `num_mods`, that was the JSON tag for a field in the `SaveHeader` struct (`NumMods`). I removed it because it wasn't used in the UI and you can just get the length of the mod array anyways.

**Comment by knoxfighter** [comment]
ah, ok, nice. In my tests also everything works great.

One last thing i noticed: Mods are shown compatible, if they are from a lower factorio-version. Mod for version 0.13 is compatible with factorio-version 0.16. Does it has mods, that are compatible to multiple game versions?? I think, it should only being shown compatible for fixes and not for minor/major versions.

**Comment by mroote** [comment]
Awesome this looks great! sorry for the delay. Thanks for this great cleanup.

**Pull request merged**
