### PR TITLE
Fix console

### PR DESCRIPTION
**Pull request by jannaahs**
I fixed the console #76.

- The Rcon session did not start, because factorio changed a log line. 
- I noticed FSM crashes after the ingame chat was used #165 => `panic: send on closed channel`

If you have trouble to load the UI and it is really slow, just delete the factorio-server-console.log 😉

### CODE REVIEW

**Comment by jannaahs** [comment]
Dear @knoxfighter @mroote 

after a lot of testing the console works again with the current UI and does not chrash factorio any more.
Maybe you can test it as well and merge the pull request.

Cheers
Jan

**Comment by knoxfighter** [comment]
> If you have trouble to load the UI and it is really slow, just delete the factorio-server-console.log
This is also something, that should be adressed in the new UI. So this does not make the browser lagg. Something like only showing the last X lines or so. But that is a different topic xD
I will look into it, tonight or tomorrow :)

**Comment by knoxfighter** [comment]
Ok, i looked into it and found multiple errors:

----------------------------
1.
When i directly open `http://127.0.0.1:8080/console` in the browser. I get multiple errors:
```
23:18:17.995 Uncaught TypeError: can't access property "emit", this.props.socket is undefined
    subscribeLogToSocket ConsoleContent.jsx:30
    componentDidMount ConsoleContent.jsx:26
    React 6
    unstable_runWithPriority scheduler.development.js:697
    React 5
    unstable_runWithPriority scheduler.development.js:697
    React 6
    success App.jsx:61
    jQuery 6
    checkLogin App.jsx:55
    componentDidMount App.jsx:39
    React 6
    unstable_runWithPriority scheduler.development.js:697
    React 10
    js index.js:36
    js bundle.js:76328
    Webpack 3
ConsoleContent.jsx:30:27
    subscribeLogToSocket ConsoleContent.jsx:30
    subscribeLogToSocket self-hosted:1171
    componentDidMount ConsoleContent.jsx:26
    componentDidMount self-hosted:1171
    React 6
    commitRootImpl self-hosted:1275
    unstable_runWithPriority scheduler.development.js:697
    React 4
    performSyncWorkOnRoot self-hosted:1218
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:697
    React 6
    success App.jsx:61
    jQuery 6
    checkLogin App.jsx:55
    checkLogin self-hosted:1171
    componentDidMount App.jsx:39
    React 6
    commitRootImpl self-hosted:1275
    unstable_runWithPriority scheduler.development.js:697
    React 10
    js index.js:36
    js bundle.js:76328
    Webpack 3
```
```
23:18:17.994 The above error occurred in the <ConsoleContent> component:
    in ConsoleContent (at App.jsx:182)
    in Route (at App.jsx:182)
    in Switch (at App.jsx:175)
    in div (at App.jsx:162)
    in App (created by Context.Consumer)
    in withRouter(App) (created by Context.Consumer)
    in Route (at ui/index.js:40)
    in Switch (at ui/index.js:38)
    in Router (created by BrowserRouter)
    in BrowserRouter (at ui/index.js:37)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:21843
    React 12
    unstable_runWithPriority scheduler.development.js:697
    React 5
    unstable_runWithPriority scheduler.development.js:697
    React 6
    success App.jsx:61
    jQuery 6
    checkLogin App.jsx:55
    componentDidMount App.jsx:39
    React 6
    unstable_runWithPriority scheduler.development.js:697
    React 10
    js index.js:36
    js bundle.js:76328
    Webpack 3
```
```
23:18:17.979 Warning: Failed prop type: The prop `socket` is marked as required in `ConsoleContent`, but its value is `undefined`.
    in ConsoleContent (at App.jsx:182)
    in Route (at App.jsx:182)
    in Switch (at App.jsx:175)
    in div (at App.jsx:162)
    in App (created by Context.Consumer)
    in withRouter(App) (created by Context.Consumer)
    in Route (at ui/index.js:40)
    in Switch (at ui/index.js:38)
    in Router (created by BrowserRouter)
    in BrowserRouter (at ui/index.js:37) checkPropTypes.js:20
    printWarning checkPropTypes.js:20
    checkPropTypes checkPropTypes.js:82
    React 2
    render App.jsx:182
    render react-router.js:447
    React 7
    unstable_runWithPriority scheduler.development.js:697
    React 6
    success App.jsx:61
    jQuery 6
    checkLogin App.jsx:55
    componentDidMount App.jsx:39
    React 6
    unstable_runWithPriority scheduler.development.js:697
    React 10
    js index.js:36
    js bundle.js:76328
    Webpack 3
```

-----------------------------------------
2.
When using the console (writing text and executing it) the output is not directly gathered, but only updated every second execution.
GO-Output
```
2020/08/17 23:35:38 Received command: test
2020/08/17 23:35:38 Command send to Factorio: test, with rcon request id: 18933
2020/08/17 23:35:38 Factorio Server: 2020-08-17 23:35:38 [CHAT] <server>: test
2020/08/17 23:35:48 Received command: test
2020/08/17 23:35:48 Command send to Factorio: test, with rcon request id: 18934
2020/08/17 23:35:48 Factorio Server: 2020-08-17 23:35:48 [CHAT] <server>: test
2020/08/17 23:35:51 Received command: test
2020/08/17 23:35:51 Command send to Factorio: test, with rcon request id: 18935
2020/08/17 23:35:51 Factorio Server: 2020-08-17 23:35:51 [CHAT] <server>: test
2020/08/17 23:35:57 Received command: test
2020/08/17 23:35:57 Command send to Factorio: test, with rcon request id: 18936
2020/08/17 23:35:57 Factorio Server: 2020-08-17 23:35:57 [CHAT] <server>: test
2020/08/17 23:36:30 Received command: \c print("test")
2020/08/17 23:36:30 Command send to Factorio: \c print("test"), with rcon request id: 18937
2020/08/17 23:36:30 Factorio Server: 2020-08-17 23:36:30 [CHAT] <server>: \c print("test")
2020/08/17 23:36:34 Received command: test
2020/08/17 23:36:34 Command send to Factorio: test, with rcon request id: 18938
2020/08/17 23:36:34 Factorio Server: 2020-08-17 23:36:34 [CHAT] <server>: test
```
Website-Output:
```
$ test
$ test
1.370 Info ServerRouter.cpp:525: Own address is IP ADDR:({2.201.158.8:34197}) (confirmed by pingpong4)
2020-08-17 23:35:38 [CHAT] <server>: test
2020-08-17 23:35:48 [CHAT] <server>: test
$ test
$ test
2020-08-17 23:35:38 [CHAT] <server>: test
2020-08-17 23:35:48 [CHAT] <server>: test
2020-08-17 23:35:51 [CHAT] <server>: test
2020-08-17 23:35:57 [CHAT] <server>: test
$ \c print("test")
$ test
2020-08-17 23:35:51 [CHAT] <server>: test
2020-08-17 23:35:57 [CHAT] <server>: test
2020-08-17 23:36:30 [CHAT] <server>: \c print("test")
2020-08-17 23:36:34 [CHAT] <server>: test
```

**Comment by knoxfighter** [comment]
1. Error is not relevant for know. We will get a completely new front-end and therefore, fixing the old one is not really timeefficient.
2. Our theory is, that it is an error within the frontend implementation, @jannaahs will look into it in the new frontend and if the error is backendside, it will be fixed here.
3. This error is a problem with the current backend implementation of the websocket and will be fixed in this PR or in a new one.

**Comment by jannaahs** [comment]
> 1. Error is not relevant for know. We will get a completely new front-end and therefore, fixing the old one is not really timeefficient.

I implemented the console on my fork. The current frontend I didn't touch.

> 2. Our theory is, that it is an error within the frontend implementation, @jannaahs will look into it in the new frontend and if the error is backendside, it will be fixed here.

There is an issue with receiving updates from the `factorio-server-console.log`. After switching from notify to poll it works.

> 3. This error is a problem with the current backend implementation of the websocket and will be fixed in this PR or in a new one.

With polling the problem seems gone.

**Comment by jannaahs** [comment]
@knoxfighter maybe you can test it?

For me it is working fine (with current and new frontend).

**Pull request merged**
