### PR TITLE
fix #123: incorrect incompatibility flags

### LINKED ISSUE #123: Mods showing as not compatible when they are
Mods loaded from a save that will function correctly if it's launched from the client show as "not compatible" in the mod list.
Did some digging and i'll use power armor MK3 as an example. Original info.json

> {
	"name":"Power Armor MK3",
	"author":"jimmy_1283",
	"version":"0.1.6",
	"title":"Power Armor MK3",
	"description":"Bigger, better power armors; with a bigger grid (14x14)/(20x20) and larger inventory bonus (+50)/(+60), also adds various equipment.",
	"homepage":"https://forums.factorio.com/viewtopic.php?f=93&t=47506",
	"factorio_version":"0.16",
	"dependencies": ["base >= 0.15.0"]
}

The above will trigger the "not compatible" flag against the mod. Had a peek through the code and it could either be the factorioversion or dependencies values causing this (as per checkModCompatibility func calls)
Checking other mods that don't flag "not compatible" and those that do, i noticed a correlation with the "dependcies" values.
If a mod has a dependency, as above `["base >= 0.15.0"]` it will flag as not compatible. If i change the info.json to 
> {
	"name":"Power Armor MK3",
	"author":"jimmy_1283",
	"version":"0.1.6",
	"title":"Power Armor MK3",
	"description":"Bigger, better power armors; with a bigger grid (14x14)/(20x20) and larger inventory bonus (+50)/(+60), also adds various equipment.",
	"homepage":"https://forums.factorio.com/viewtopic.php?f=93&t=47506",
	"factorio_version":"0.16",
    "dependencies": ["base >= 0.16"]
}

The mod will show as compatible. It doesn't seem to correlate with the client being able to load and run these mods without issue.

Unfortunately I don't know enough to put up a PR but i wonder if this is the point at which a cchange might be prudent: mod_modInfo.go - Line 87 - `baseDependency = strings.Split(dependency, "=")[1]`

If the base dependency is split on '=' it won't have the > when run through semver thus a valid `"dependencies": ["base >= 0.15.0"]` would be evaled on "= 0.15.0" and thus throw the "not compatible".
or i could be way off :)

### LINKED ISSUE #124: Downloading Mods with Space Or Underscore in ID breaks mod section
Seems like downloading mods with a Space or an Underscore in their name breaks the mod section. It won't show what mods you have installed or let you add anymore.

Running in the latest docker container on Ubuntu 18.04 system.

Offending Mods: 
[Squeak Through](https://mods.factorio.com/mod/Squeak%20Through)
[Power Armor MK3](https://mods.factorio.com/mod/Power%20Armor%20MK3)
[Big_Brother](https://mods.factorio.com/mod/Big_Brother)

Probably more than this, just the ones I tried.

```
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:230 +0x65e,
2018/10/20 03:22:46 download complete,
	/usr/lib/go/src/net/http/server.go:2795 +0x27b,
	/usr/lib/go/src/net/http/server.go:1830 +0x651,
created by net/http.(*Server).Serve,
net/http.(*conn).serve(0xc4203483c0, 0x8a5480, 0xc420028100),
	/usr/lib/go/src/net/http/server.go:2694 +0xbc,
net/http.serverHandler.ServeHTTP(0xc42009f040, 0x8a50c0, 0xc420453880, 0xc42060a200),
	/home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc,
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420632410, 0x8a50c0, 0xc420453880, 0xc42060af00),
	/usr/lib/go/src/net/http/server.go:1947 +0x44,
net/http.HandlerFunc.ServeHTTP(0xc42062c7e0, 0x8a50c0, 0xc420453880, 0xc42060af00),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233,
main.AuthorizeHandler.func1(0x8a50c0, 0xc420453880, 0xc42060af00),
net/http.HandlerFunc.ServeHTTP(0x86d778, 0x8a50c0, 0xc420453880, 0xc42060af00),
main.ModPortalInstallHandler(0x8a50c0, 0xc420453880, 0xc42060af00),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:160 +0x588,
main.(*Mods).downloadMod(0xc4203d8690, 0xc4201ba5c0, 0x35, 0xc42031e04a, 0x1d, 0xc42031e070, 0x12, 0x0, 0x0),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:113 +0xcc,
main.(*Mods).createMod(0xc4203d8690, 0xc42031e070, 0x12, 0xc42031e04a, 0x1d, 0x8a1680, 0xc4202d24c0, 0xc420022840, 0x12),
goroutine 342 [running]:,
net/http.(*conn).serve.func1(0xc4203483c0),
panic(0x7cff00, 0xa72970),
	/usr/lib/go/src/runtime/panic.go:502 +0x229,
	/usr/lib/go/src/net/http/server.go:1726 +0xd0,
main.(*ModInfoList).listInstalledMods.func1(0xc42049b710, 0x30, 0x8a6820, 0xc420254820, 0x0, 0x0, 0x0, 0x0),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892,
	/usr/lib/go/src/path/filepath/path.go:357 +0x402,
path/filepath.walk(0xc42049b710, 0x30, 0x8a6820, 0xc420254820, 0xc420246e80, 0x0, 0x0),
path/filepath.walk(0xc420022840, 0x12, 0x8a6820, 0xc4201c1110, 0xc420246e80, 0x0, 0x10),
	/usr/lib/go/src/path/filepath/path.go:381 +0x2c2,
path/filepath.Walk(0xc420022840, 0x12, 0xc420246e80, 0xa7f560, 0xc42001fbf0),
	/usr/lib/go/src/path/filepath/path.go:403 +0x106,
main.(*ModInfoList).listInstalledMods(0xc4203d86b8, 0xc4207232f0, 0x30),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97,
main.(*ModInfoList).createMod(0xc4203d86b8, 0xc42031e070, 0x12, 0xc42031e04a, 0x1d, 0x8a1680, 0xc4202d24c0, 0x0, 0x0),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:205 +0x3fb,
2018/10/20 03:22:46 http: panic serving 172.17.0.16:47860: runtime error: index out of range,
 Status: 200 OK,
 StatusCode: 200,
2018/10/20 03:22:46 error finding basemodDependency. Using FactorioVersion...,
2018/10/20 03:22:31 error finding basemodDependency. Using FactorioVersion...,
2018/10/20 03:22:31 completed copying the response.Body
```

Mods also aren't added to modlist.json even though they are downloaded succesfully.

### PR DESCRIPTION
**Pull request by sean-callahan**
Simplified base dependency checking for mod.json. Fixes #123 and should fix #124.

### CODE REVIEW

**Comment by knoxfighter** [comment]
Hi, thank very much for fixing my mistakes. I also started yesterday to think about this issues, but you were faster :)
I pulled it and tested multiple scenarios. There i found two problems:
1. Some mods dont define a version and only have "base" as their dependency. So instead of ~~"dependencies": ["base >= 0.14.0"]~~ they use just _"dependencies": ["base"]_
2. It seems like the frontend has problems in reading the versions and especially the Add Mod Section has no more compatibility markers.

**Comment by sean-callahan** [comment]
1. I didn't know you can specify a dependency without a version. Thanks for pointing that out.

Let me know if you find anymore issues with my updated changes. Thank you for testing!

**Comment by knoxfighter** [comment]
That looks good now, i cant find any more bugs. 
Is it a good idea, to use your new Version struct to also calculate compatibility and versions in the factorioSave package?

**Comment by mroote** [comment]
Awesome thanks for the fix @sean-callahan and thanks for testing @knoxfighter. Looks like it's good to merge?

Makes sense to switch to the Version struct, that's a nice addition!

**Comment by knoxfighter** [comment]
@mroote depends, if we want to use the Versions struct also in the factorioSave package. We can also do that in a different PR. Your decision :)

**Comment by mroote** [comment]
This PR fixes the one issue so I think it's good to merge it in now.  We can make a separate PR to switch to the new struct. Thanks again all!

**Pull request merged**
