### PR TITLE
Add dockerfile to build releases

### PR DESCRIPTION
**Pull request by mroote**
Added a dockerfile to create the release packages and added a CI job to automatically upload releases if you tag the version.

### CODE REVIEW

**Comment by knoxfighter** [comment]
It seems, like only go-1.10.x is tested!

**Comment by mroote** [comment]
I got it working with multiple go versions now and removed some of the older versions. Windows seems to have issues making the builds though not sure what's up with that.

**Comment by knoxfighter** [comment]
Windows has no "make" command: "/c/Users/travis/.travis/functions: line 104: make: command not found"
And the release should only work, when running on master-branch and successfully, in my opinion. Cause you crated a new Release, with this script (with wrong Patchnotes)

**Comment by knoxfighter** [comment]
It took me some time, but know, i can understand travis files :)
I looked into this and tested it on my fork.
It has no make on windows. So the installation cannot be done with `make godeps`. Please change it to the install-step and manually added.

**Comment by mroote** [comment]
That 0.8.3 release was just a tag created while I was testing by mistake, I've removed it now.

Nice yeah I'll have to update the build to use Go to download the deps. I'll look into migrating the deps to use Go modules instead now.

**Comment by knoxfighter** [comment]
I also thought about using go deps instead, but when you do it, it is fine for me.
Also, the 0.8.2 release is based on this PR, not based on the master or develop-branch. I would say, we should create a new release, from the develop-branch and with a proper changelog :)

**Comment by mroote** [comment]
Yeah I agree once this build is working I'll merge this in and make a proper build off of develop.

**Pull request merged**
